package twitter.graphs.stylized;

import java.util.List;

/**
* Any stylized graph generated by a graph generator.
*/
public interface StylizedGraph {
  /**
  * @param userID The index of the user whose friends we want to get.
  * @return the list of IDs of the users friends.
  */
	public List<Integer> getUsersFollowers(int userID);
  /**
  * @param userID The index of the user whose followers we want to get.
  * @return the list of IDs of the users followers.
  */
	public List<Integer> getUsersFriends(int userID);
}
