package project;

import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class TwitterModel extends ViewableDigraph {

	public TwitterModel(){
		this("Twitter Model");
	}
	
	public TwitterModel(String name) {
		super(name);
		
		addOutport("OUT_TAG");
		addOutport("OUT_TWEET");
		
		ViewableAtomic g = new TweetG();
		ViewableAtomic tm = new TweetCreator();
		
		add(g);
		add(tm);
		
		addCoupling(g, TweetG.OUT_SETTINGS, tm, TweetCreator.IN_CONFIG);
		addCoupling(g, TweetG.OUT_TWTCMD, tm, TweetCreator.IN_TWEETCOMMAND);
		
		addCoupling(tm, TweetCreator.OUT_TWEET, this, "OUT_TWEET");
		
	}

	
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(591, 332);
        ((ViewableComponent)withName("ViewableAtomic")).setPreferredLocation(new Point(222, 188));
        ((ViewableComponent)withName("Tweet Gen")).setPreferredLocation(new Point(50, 50));
    }
}
